/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/cyTBCHOec20
 */
import { Button } from "@/components/ui/button"

export function LandingPage() {
  return (
    <div className="min-h-screen bg-[#282a36] text-[#f8f8f2] flex flex-col items-center justify-center p-4">
      <header className="absolute top-0 left-0 right-0 flex justify-between items-center p-4">
        <div className="flex items-center space-x-4">
          <img alt="Logo" className="h-20 invert" src="/Typing-Project-Logo.svg" />
          <h1 className="text-xl text-[#50fa7b] font-bold">TypeTutor</h1>

          <div className="flex space-x-2 rounded-full bg-[#3a3d4d]">
            <Button className="text-xs text-[#50fa7b]" variant="ghost">
              <PencilIcon className="text-[#f8f8f2] h-4 w-4" />
            </Button>
            <Button className="text-xs text-[#50fa7b]" variant="ghost">
              <CalculatorIcon className="text-[#f8f8f2] h-4 w-4" />
            </Button>
            <Button className="text-xs text-[#50fa7b]" variant="ghost">
              <ClockIcon className="text-[#f8f8f2] h-4 w-4" />
            </Button>
            <Button className="text-xs text-[#50fa7b]" variant="ghost">
              <WholeWordIcon className="text-[#f8f8f2] h-4 w-4" />
            </Button>
            <Button className="text-xs text-[#50fa7b]" variant="ghost">
              <QuoteIcon className="text-[#f8f8f2] h-4 w-4" />
            </Button>
          </div>
        </div>
        <div className="flex items-center space-x-4">
          <Button variant="ghost">
            <SearchIcon className="text-[#f8f8f2] h-5 w-5" />
          </Button>
          <Button variant="ghost">
            <SignalIcon className="text-[#f8f8f2] h-5 w-5" />
          </Button>
          <Button variant="ghost">
            <HelpCircleIcon className="text-[#f8f8f2] h-5 w-5" />
          </Button>
        </div>
      </header>
      <main className="flex flex-col items-center justify-center space-y-10 p-10">
        <h1 className="text-6xl font-bold text-[#50fa7b]">TypeTutor</h1>
        <p className="text-lg text-[#6272a4]">A machine learning typing tutor</p>
        <div className="text-5xl font-mono space-y-4">
          <p>
            early when where child must on and call well house small own a at interest own go program form way early old
            problem be
          </p>
        </div>
      </main>
      <footer className="absolute bottom-4">
        <div className="flex space-x-2 text-sm">
          <Button className="text-[#6272a4]" variant="ghost">
            tab + enter - restart test
          </Button>
          <Button className="text-[#6272a4]" variant="ghost">
            esc or cmd + shift + p - command line
          </Button>
        </div>
      </footer>
    </div>
  )
}


function PencilIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17 3a2.85 2.83 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5Z" />
      <path d="m15 5 4 4" />
    </svg>
  )
}


function CalculatorIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="16" height="20" x="4" y="2" rx="2" />
      <line x1="8" x2="16" y1="6" y2="6" />
      <line x1="16" x2="16" y1="14" y2="18" />
      <path d="M16 10h.01" />
      <path d="M12 10h.01" />
      <path d="M8 10h.01" />
      <path d="M12 14h.01" />
      <path d="M8 14h.01" />
      <path d="M12 18h.01" />
      <path d="M8 18h.01" />
    </svg>
  )
}


function ClockIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24" 
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <polyline points="12 6 12 12 16 14" />
    </svg>
  )
}



function WholeWordIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="7" cy="12" r="3" />
      <path d="M10 9v6" />
      <circle cx="17" cy="12" r="3" />
      <path d="M14 7v8" />
      <path d="M22 17v1c0 .5-.5 1-1 1H3c-.5 0-1-.5-1-1v-1" />
    </svg>
  )
}


function QuoteIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 21c3 0 7-1 7-8V5c0-1.25-.756-2.017-2-2H4c-1.25 0-2 .75-2 1.972V11c0 1.25.75 2 1 1v1c0 1-1 2-2 2s-1 .008-1 1.031V20c0 1z" />
      <path d="M15 21c3 0 7-1 7-8V5c0-1.25-.757-2.017-2-2h-4c-1.25 0-2 .75-2 1.972V11c0 1.25.75 2 2h.75c0 2.25.25 4-2.75 4v3c0 1 1z" />
    </svg>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function SignalIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2 20h.01" />
      <path d="M7 20v-4" />
      <path d="M12 20v-8" />
      <path d="M17 20V8" />
      <path d="M22 4v16" />
    </svg>
  )
}


function HelpCircleIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3" />
      <path d="M12 17h.01" />
    </svg>
  )
}