/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/tJXFF5OCT2C
 */

import { Button } from "@/components/ui/button"
import { DividerVerticalIcon } from "@radix-ui/react-icons"

export function LandingPage() {
  return (
    <div className="min-h-screen bg-[#282a36] text-[#f8f8f2] flex flex-col items-center justify-center p-4">
      <header className="absolute top-0 left-0 right-0 flex justify-between items-center p-4">
        <div className="flex items-center space-x-4">
            <img alt="Logo" className="h-16 invert" src="/Typing-Project-Logo.svg" />
          <div className="flex space-x-2">
            <Button className="text-xs text-[#50fa7b]" variant="ghost">
              @ punctuation
            </Button>
            <Button className="text-xs text-[#50fa7b]" variant="ghost">
              # numbers
            </Button>
            
            <DividerVerticalIcon className="text-white h-10 divider-icon" />
            <Button className="text-xs text-[#50fa7b]" variant="ghost">
              time
            </Button>
            <Button className="text-xs text-[#50fa7b]" variant="ghost">
              words
            </Button>
            <Button className="text-xs text-[#50fa7b]" variant="ghost">
              quote
            </Button>
            <Button className="text-xs text-[#50fa7b]" variant="ghost">
              zen
            </Button>
            <Button className="text-xs text-[#50fa7b]" variant="ghost">
              custom
            </Button>
          </div>
        </div>
        <div className="flex items-center space-x-4">
          <Button variant="ghost">
            <SettingsIcon className="text-[#f8f8f2]" />
          </Button>
          <Button variant="ghost">
            <UserIcon className="text-[#f8f8f2]" />
          </Button>
          <Button variant="ghost">
            <TypeIcon className="text-[#f8f8f2]" />
          </Button>
        </div>
      </header>
      <main className="flex flex-col items-center justify-center space-y-4">
        <h1 className="text-6xl font-bold">TypeMaster</h1>
        <p className="text-lg text-[#6272a4]">A machine learning typing tutor</p>
        <div className="text-5xl font-mono space-y-4">
          <p>
            early when where child must on and call well house small own a at interest own go program form way early old
            problem be
          </p>
        </div>
      </main>
      <footer className="absolute bottom-4">
        <div className="flex space-x-2 text-sm">
          <Button className="text-[#6272a4]" variant="ghost">
            tab + enter - restart test
          </Button>
          <Button className="text-[#6272a4]" variant="ghost">
            esc or cmd + shift + p - command line
          </Button>
        </div>
      </footer>
    </div>
  )
}


function SettingsIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12.22 2h-.44a2 2 0 0-2 2v.18a2 1-1 1.73l-.43.25a2 1-2 0l-.15-.08a2 0-2.73.73l-.22.38a2 .73 2.73l.15.1a2 1 1.72v.51a2 1.74l-.15.09a2 0-.73 2.73l.22.38a2 2.73.73l.15-.08a2 0l.43.25a2 1.73V20a2 2h.44a2 2-2v-.18a2 1-1.73l.43-.25a2 0l.15.08a2 2.73-.73l.22-.39a2 0-.73-2.73l-.15-.08a2 1-1-1.74v-.5a2 1-1.74l.15-.09a2 .73-2.73l-.22-.38a2 0-2.73-.73l-.15.08a2 0l-.43-.25a2 1-1-1.73V4a2 0-2-2z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  )
}


function UserIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0-4-4H9a4 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}


function TypeIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="4 7 20" />
      <line x1="9" x2="15" y1="20" y2="20" />
      <line x1="12" x2="12" y1="4" y2="20" />
    </svg>
  )
}
