import React, { useState, useEffect } from "react";

export default function TypingTest() {
  const [text, setText] = useState("Sample Text for Typing Test");
  const [userInput, setUserInput] = useState("");
  const [timer, setTimer] = useState(30);
  const [isRunning, setIsRunning] = useState(false);
  const [wordsCorrect, setWordsCorrect] = useState(0);
  const [wpm, setWpm] = useState(0);
  const [accuracy, setAccuracy] = useState(0);
  const [consistency, setConsistency] = useState(0);
  const [correct, setCorrect] = useState(true);
  const [incorrect, setIncorrect] = useState(false);

  useEffect(() => {
    let interval: NodeJS.Timeout;
    if (isRunning && timer > 0) {
      interval = setInterval(() => {
        setTimer((prevTimer) => prevTimer - 1);
      }, 1000);
    } else if (timer === 0) {
      setIsRunning(false);
      // Calculate WPM, Accuracy, and Consistency here
      setWpm(wordsCorrect / 2 / timer);
    }
    return () => clearInterval(interval);
  }, [isRunning, timer]);

  const handleInputChange = (event: any) => {
    if (!isRunning) return;
    const input = event.target.value;
    setUserInput(input);

    // Add logic for real-time accuracy, WPM calculation here
  };

  function generateText(wordCount = 300) {
    const wordBag = [
      "the",
      "of",
      "and",
      "a",
      "to",
      "in",
      "is",
      "you",
      "that",
      "it",
      "he",
      "was",
      "for",
      "on",
      "are",
      "as",
      "with",
      "his",
      "they",
      "at",
      "be",
      "this",
      "have",
      "friend",
      "happy",
      "sky",
      "beautiful",
      "run",
      "walk",
      "think",
      "dream",
      "light",
      "dark",
      "day",
      "night",
      "sun",
      "moon",
      "love",
      "hope",
      "peace",
      "chaos",
      "life",
      "death",
      "world",
      "heart",
      "mind",
      "soul",
      "joy",
      "sad",
      "angry",
      "calm",
      "storm",
      "sea",
      "mountain",
      "river",
      "stream",
      "forest",
      "tree",
      "leaf",
      "flower",
      "grass",
      "bird",
      "fish",
      "animal",
      "dog",
      "cat",
      "mouse",
      "elephant",
      "lion",
      "tiger",
      "bear",
      "wolf",
      "fox",
      "rabbit",
      "snake",
      "insect",
      "butterfly",
      "bee",
      "ant",
      "spider",
      "city",
      "town",
      "village",
      "country",
      "world",
      "planet",
      "universe",
      "star",
      "galaxy",
      "space",
      "time",
      "moon",
      "water",
      "fire",
      "earth",
      "air",
      "magic",
      "mystery",
      "adventure",
      "journey",
      "quest",
      "battle",
      "war",
      "peace",
      "king",
      "queen",
      "prince",
      "princess",
      "wizard",
      "witch",
      "dragon",
      "monster",
      "hero",
      "villain",
      "legend",
      "myth",
      "fairy",
      "tale",
      "story",
      "book",
      "novel",
      "poem",
      "song",
      "dance",
      "art",
      "painting",
      "sculpture",
      "music",
      "theater",
      "film",
      "movie",
      "video",
      "apple",
      "banana",
      "orange",
      "grape",
      "strawberry",
      "melon",
      "pineapple",
      "kiwi",
      "peach",
      "pear",
      "cherry",
      "plum",
      "watermelon",
      "mango",
      "lemon",
      "lime",
      "coconut",
      "berry",
      "vegetable",
      "carrot",
      "broccoli",
      "cucumber",
      "tomato",
      "potato",
      "onion",
      "pepper",
      "lettuce",
      "spinach",
      "garlic",
      "eggplant",
      "zucchini",
      "celery",
      "cabbage",
      "mushroom",
      "avocado",
      "peanut",
      "almond",
      "walnut",
      "cashew",
      "pistachio",
      "honey",
      "bread",
      "butter",
      "cheese",
      "milk",
      "yogurt",
      "egg",
      "chicken",
      "beef",
      "pork",
      "fish",
      "shrimp",
      "lobster",
      "crab",
      "rice",
      "pasta",
      "noodle",
      "soup",
      "sandwich",
      "pizza",
      "burger",
      "fries",
      "cookie",
      "cake",
      "pie",
      "chocolate",
      "ice cream",
      "coffee",
      "tea",
      "juice",
      "soda",
      "water",
      "glass",
      "cup",
      "plate",
      "fork",
      "knife",
      "spoon",
      "napkin",
      "table",
      "chair",
      "bed",
      "couch",
      "desk",
      "bookshelf",
      "lamp",
      "clock",
      "mirror",
      "window",
      "door",
      "car",
      "bicycle",
      "bus",
      "train",
      "plane",
      "ship",
      "boat",
      "subway",
      "taxi",
      "walk",
      "run",
      "swim",
      "jump",
      "dance",
      "sing",
      "laugh",
      "cry",
      "smile",
      "frown",
      "whisper",
      "shout",
      "listen",
      "speak",
      "read",
      "write",
      "learn",
      "teach",
      "study",
      "work",
      "play",
      "create",
      "explore",
      "discover",
      "travel",
      "journey",
      "adventure",
      "dream",
      "imagine",
      "plan",
      "organize",
      "achieve",
      "succeed",
      "fail",
      "try",
      "risk",
      "explore",
      "wonder",
      "ponder",
      "reflect",
      "remember",
      "forget",
      "forgive",
      "apologize",
      "understand",
      "empathize",
      "forgive",
      "appreciate",
      "value",
      "cherish",
      "admire",
      "respect",
      "hate",
      "dislike",
      "argue",
      "fight",
      "compete",
      "cooperate",
      "support",
      "encourage",
      "inspire",
      "motivate",
      "challenge",
      "celebrate",
      "party",
      "holiday",
      "celebration",
      "tradition",
      "culture",
      "heritage",
      "family",
      "friendship",
      "relationship",
      "marriage",
      "parent",
      "child",
      "sibling",
      "cousin",
      "uncle",
      "aunt",
      "grandparent",
      "neighbor",
      "stranger",
      "community",
      "society",
      "culture",
      "artistic",
      "creative",
      "scientific",
      "technological",
      "innovative",
      "historic",
      "ancient",
      "modern",
      "traditional",
      "contemporary",
      "digital",
      "analog",
      "abstract",
      "realistic",
      "fantasy",
      "fiction",
      "nonfiction",
      "history",
      "science",
      "mathematics",
      "language",
      "communication",
      "expression",
      "emotion",
      "perception",
      "sensation",
    ];

    let text = "";

    for (let i = 0; i < wordCount; i++) {
        const randomIndex = Math.floor(Math.random() * wordBag.length);
        text += wordBag[randomIndex] + " ";
    }

    setText(text);
  }


  const startTest = () => {
    setIsRunning(true);
    setWpm(0);
    setAccuracy(0);
    setConsistency(0);
    setTimer(30);
    setUserInput("");
    setWordsCorrect(0);
    setCorrect(true);
    setIncorrect(false);
    generateText();
  };

  return (
    <div>
      <h1>Typing Test</h1>
      <textarea
        value={userInput}
        className="text-black"
        onChange={handleInputChange}
      />
      <p>{text}</p>

      <p>Timer: {timer}</p>
      <p>WPM: {wpm}</p>
      <p>Accuracy: {accuracy}</p>
      <p>Consistency: {consistency}</p>
    </div>
  );
}
